Updated the logic to fail the pipeline with exit code 1 in the end after sending the results to accuknox saas when soft fail is false. & updated the readme file

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -12,7 +12,7 @@ inputs:
     description: "Do not display code blocks in output"
     required: false
   quiet:
-    description: "display only failed checks"
+    description: "Display only failed checks"
     required: false
   output_format:
     description: "The format of the output. cli, json, junitxml, github_failed_only, or sarif (comma separated)"
@@ -23,10 +23,10 @@ inputs:
     required: false
     default: "./results.json"
   soft_fail:
-    description: "do not return an error code if there are failed checks"
+    description: "Do not return an error code if there are failed checks"
     required: false
   framework:
-    description: "Run only on a specific infrastructure, Supported: Kuberenetes & Terraform"
+    description: "Run only on a specific infrastructure, Supported: Kubernetes & Terraform"
     required: false
   skip_framework:
     description: "Skip a specific infrastructure"
@@ -41,6 +41,9 @@ inputs:
     description: "The URL of the CSPM panel to push the scan results to."
     required: true
     default: "cspm.demo.accuknox.com"
+  label:
+    description: "The label created in AccuKnox SaaS for associating scan results."
+    required: true
 
 branding:
   icon: "shield"
@@ -72,12 +75,30 @@ runs:
         INPUT_SOFT_FAIL: ${{ inputs.soft_fail }}
         INPUT_FRAMEWORK: ${{ inputs.framework }}
 
-    - name: Formating the results
+      continue-on-error: true
+
+    - name: Formatting the results
       run: |
         jq --arg repoLink "${{ github.server_url }}/${{ github.repository }}" --arg branch "${{ github.ref == 'refs/heads/main' && 'main' || github.head_ref }}" '. += [{"details": {"repo": $repoLink, "branch": $branch}}]' results/results_json.json > temp.json && mv temp.json results.json
       shell: bash
 
     - name: Push report to CSPM panel
       run: |
-        curl --location --request POST 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=IAC&save_to_s3=false' --header 'Tenant-Id: ${{ inputs.tenant_id  }}' --header 'Authorization: Bearer ${{ inputs.token }}' --form 'file=@"results.json"'
+        curl --location --request POST 'https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=IAC&label_id=${{ inputs.label }}&save_to_s3=false' --header 'Tenant-Id: ${{ inputs.tenant_id }}' --header 'Authorization: Bearer ${{ inputs.token }}' --form 'file=@"results.json"'
+      shell: bash
+
+    - name: Capture Checkov exit code
+      id: capture-exit-code
+      run: |
+        echo "Checkov exit code: ${{ steps.checkov-scan.outcome }}"
+        if [ "${{ steps.checkov-scan.outcome }}" == "failure" ]; then
+          echo "checkov_failed=true" >> $GITHUB_ENV
+        fi
+      shell: bash
+
+    - name: Fail pipeline at the end if Checkov scan failed
+      if: env.checkov_failed == 'true'
+      run: |
+        echo "Checkov scan failed. Exiting with failure."
+        exit 1
       shell: bash
